// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGGjmb-4_3nPiOesUFJknSmpwdD_6jGOk',
    appId: '1:845541325512:web:7e3ad1242ce9f01d7f83fd',
    messagingSenderId: '845541325512',
    projectId: 'hyzar-storage',
    authDomain: 'hyzar-storage.firebaseapp.com',
    databaseURL: 'https://hyzar-storage-default-rtdb.firebaseio.com',
    storageBucket: 'hyzar-storage.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhiCeZG4_9zWp-D7seG7WBPX7W3C54Elg',
    appId: '1:845541325512:android:937b28f26fc228707f83fd',
    messagingSenderId: '845541325512',
    projectId: 'hyzar-storage',
    databaseURL: 'https://hyzar-storage-default-rtdb.firebaseio.com',
    storageBucket: 'hyzar-storage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6wt5qXnvIlVBLx_OEJn1ar5g2KXG8TIU',
    appId: '1:845541325512:ios:808f4eb8ad2d3a0c7f83fd',
    messagingSenderId: '845541325512',
    projectId: 'hyzar-storage',
    databaseURL: 'https://hyzar-storage-default-rtdb.firebaseio.com',
    storageBucket: 'hyzar-storage.appspot.com',
    iosClientId: '845541325512-anmn9go14fcvlu34o3fvl3emqb6bv1cn.apps.googleusercontent.com',
    iosBundleId: 'com.m1ttt.storage',
  );
}
